### ISSUE TITLE
Unable to use lunchable as CLI

### ISSUE THREAD

**Issue by felippecaso** [juftin/lunchable#111]
-   lunchable version: `1.1.0`
-   Python version: `3.12.1`
-   Operating System: MacOS

### Description

I tried to install and use Lunchable as a CLI without trying it as a package. The steps I expected to be enough for making it work were:
1. Having the `LUNCHMONEY_ACCESS_TOKEN` variable available;
2. Executing any `lunchable` command in a shell with the package installed.

In all trials (detailed below) I got a `ModuleNotFoundError: No module named 'numpy'`. As a hypothesis, I believe it can have to do with the combination of the ways I installed it and the fact that `pandas` (and therefore `numpy`) is a optional dependency in `pyproject.toml`.
I eventually made it work by manually running `poetry add pandas` to my project.

I expected to be able to use Lunchable's CLI directly from the installation methods I chose, which are analogous to `pip install`.

### What I Did

**Trial 1**
```
pipx install lunchable
lunchable --version
```

**Trial 2** (in a poetry project)
```
poetry add lunchable
poetry install
poetry run lunchable --version
```

In both trials, the env variable `LUNCHMONEY_ACCESS_TOKEN` was available, and both returned the `ModuleNotFoundError`.

**Comment by juftin** [comment]
Which CLI command are you running?

If you're using a plugin like PrimeLunch you'll need to install with extras. 

I recommend the "all" extras:

pipx install "lunchable[all]"

**Comment by juftin** [comment]
Hey @felippecaso @Lilneo786 sorry for the troubles. There are two plugins on the CLI that require extra packages to be installed: `primelunch` and `splitlunch`. I've fixed the CLI so you will only encounter an `ImportError` when trying to run these plugins specifically. If you're interested in the plugins I recommend running the following command to get all the extra packages:

```shell
pipx install "lunchable[all]"
```

**Comment by felippecaso** [comment]
Awesome, @juftin! Thanks for the response and for the patch

**Comment by juftin** [comment]
Just a follow up here, lunchable's plugins have been moved into their own separate packages outside of the main lunchable repo:

- [PushLunch](https://github.com/juftin/lunchable-pushlunch): Push Notifications via Pushover
- [SplitLunch](https://github.com/juftin/lunchable-splitlunch): Splitwise Integration
- [PrimeLunch](https://github.com/juftin/lunchable-primelunch): Amazon Transaction Updater

They're all still accessible from the `lunchable` CLI as long as they're installed into the same environment as lunchable via a new plugin framework. 

If you're interested in using these plugins the best way to install them is using the `plugins` extra (the `all` extra still works too):

```shell
pipx install "lunchable[all]"
```

And to access them from the command line:

```
lunchable plugins ...
```
