### ISSUE TITLE
Assets Validation Error on Nulls in 'balance_as_of' field in Assets

### ISSUE THREAD

**Issue by jcsacto** [juftin/lunchable#113]
-   lunchable version:  1.1.1
-   Python version: 3.8.18
-   Operating System: Windows 11

### Description

Describe what you were trying to get done.
Trying to execute the lunch.get_assets command

Tell us what happened, what went wrong, and what you expected to happen.

Received an error shown below: 

ValidationError: 1 validation error for AssetsObject
balance_as_of
  Input should be a valid datetime [type=datetime_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.5/v/datetime_type

It appears the issue is LunchMoney allows assets to have NULLs in the balance_as_of field for manually created assets, but when Lunchable calls them it doesn't like it.  

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by juftin** [comment]
Dang, that's supposed to be non-nullable according to the documentation https://lunchmoney.dev/#assets-object. Fix on the way

**Comment by jcsacto** [comment]
Thanks @juftin , confirmed the get_assets endpoint is working as expected now!
