### ISSUE TITLE
Trying to insert a duplicated transaction causes JSONDecodeError

### ISSUE THREAD

**Issue by chachan** [juftin/lunchable#89]
-   lunchable version: 0.9.0
-   Python version: 3.10
-   Operating System: Debian GNU/Linux 12

### Description

I insert transactions to LM manually since my bank does not provide any API. I weekly download last 30 days transaction list in CSV format file and process it using custom scripts. Most of transactions are duplicated and I'm ok with that since I ensure transaction IDs are unique.

### What I Did

When trying to insert duplicated transaction it seems like API is now responding with empty content and 204 status code, since lunchable expects JSON content then it is breaking with error: 
```JSONDecodeError('Expecting value: line 1 column 1 (char 0)')``` in https://github.com/juftin/lunchable/blob/f33ed20eadb44641d5737d5611ad7e03d274400d/lunchable/models/_core.py#L127

**Comment by juftin** [comment]
Hey @chachan - I will look into this. For my debugging, what made the transaction "duplicated"? Was everything the same or just the external ID?

I ran the following code multiple times and wasn't able to replicate the error - instead the LunchMoney API declined to create new transactions after the first time and all responses were 200.

```python
import datetime

from lunchable import LunchMoney
from lunchable.models import TransactionInsertObject

if __name__ == "__main__":
    lunch = LunchMoney(access_token="xxxxxxxx")
    new_transaction = TransactionInsertObject(payee="Example Restaurant",
                                              amount=120.00,
                                              notes="Saturday Dinner",
                                              date=datetime.date.today(),
                                              external_id="1234")
    new_transaction_ids = lunch.insert_transactions(transactions=new_transaction)
```

Do you have any more details / code I could use to replicate?

**Comment by juftin** [comment]
https://github.com/juftin/lunchable/commit/d58437272de2e9c41d277fdd67299a3a7665449d could resolve this - but I'm not sure if this isn't actually a LunchMoney bug. I saw your thread in the Discord and will follow there. The previous response of `{"ids": []}` seems more intuitive to me.

**Comment by chachan** [comment]
@juftin , correct. A duplicated transaction is when `external_id` already exists in LM. Looked at your commit and makes sense. And agree it doesn't look like a LM bug but a different response.Thank you so much :)

**Comment by chachan** [comment]
Looks like another place is also expecting a dict

```
  File "/home/__/.cache/pypoetry/virtualenvs/lunchcr-UnUZhfHU-py3.10/lib/python3.10/site-packages/lunchable/models/transactions.py", line 760, in insert_transactions
    ids: List[int] = response_data["ids"]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by chachan** [comment]
Created this - https://github.com/juftin/lunchable/pull/107/
I tested it locally and now I can add new transactions and skip duplicates without any problem :)

**Comment by juftin** [comment]
Closed by https://github.com/juftin/lunchable/pull/107

🤔 @lunchbag I pinged you on discord but thought you might be able to jump in here and clarify. Is `POST v1/transactions` expected to return an empty 204 response when duplicate transactions are inserted or could that be a bug? I'm unable to replicate the issue on my end and get a 200 response with  `{"ids": []}` instead
